

INSERT INTO `document` (`id`, `id_image`, `titre`, `description_doc`, `code`, `etat`, `id_genre`, `type`) VALUES
(NULL, 1, 'La Flèche noire', 'Robert Louis Stevenson, 1886', 'LRS5L', 0, 5, 'livre'),
(NULL, 2, 'La Maison à vapeur', 'Jules Verne, 1880', 'LJV5L', 0, 5, 'livre'),
(NULL, 3, 'Voyage au centre de la Terre', 'Jules Verne, 1867', 'VJV5L', 0, 5, 'livre'),
(NULL, 4, 'Madame Bovary', 'Gustave Flaubert, 1857', 'MGF4L', 0, 4, 'livre'),
(NULL, 5, 'Germinal ', 'Emile Zola, 1885', 'GEZ4L', 0, 4, 'livre'),
(NULL, 6, 'Robinson Crusoé', 'Daniel Defoe, 1719', 'RDD5L', 0, 5, 'livre'),
(NULL, 7, 'Ma vie aventureuse ', 'Arthur Conan Doyle, 1932', 'MAD1L', 0, 1, 'livre'),
(NULL, 8, 'Une autobiographie', 'Agatha Christie, 1977', 'UAC1L', 0, 1, 'livre'),
(NULL, 9, 'Le chien des Baskerville ', 'Arthur Conan Doyle, 1902', 'LAD2L', 0, 2, 'livre'),
(NULL, 10, 'Double assassinat dans la rue Morgue', 'Edgar Allan Poe, 1841', 'DEP2L', 0, 2, 'livre'),
(NULL, 11, ' Le crime de l’Orient Express', 'Agatha Christie, 1934', 'LAC2L', 0, 2, 'livre'),
(NULL, 12, 'Le mystère de la chambre Jaune', 'Gaston Leroux, 1907', 'LGL2L', 0, 2, 'livre'),
(NULL, 13, 'Le Vieil Homme et la Guerre', 'John Scalzi, 2005', 'LJS3L', 0, 3, 'livre'),
(NULL, 14, 'Fondation', 'Isaac Asimov, 1951', 'FIA3L', 0, 3, 'livre'),
(NULL, 15, 'Fahrenheit 451', 'Ray Bradbury, 1953', 'FRB3L', 0, 3, 'livre'),
(NULL, 16, 'American Sniper ', 'Chris Kyle, 2012', 'ACK1L', 0, 1, 'livre'),
(NULL, 17, 'Nevermind', 'Nirvana, 1991 ', 'NDN6C', 0, 6, 'CD'),
(NULL, 18, 'The Dark Side of the Moon', 'Pink Floyd, 1973', 'TNF6C', 0, 6, 'CD'),
(NULL, 19, 'Highway to Hell', 'AC/DC, 1979 ', 'HLA6C', 0, 6, 'CD'),
(NULL, 20, 'Back in Black', 'AC/DC, 1980 ', 'BKA6C', 0, 6, 'CD'),
(NULL, 21, 'Abbey Road', 'The Beatles, 1969 ', 'ADB7C', 0, 7, 'CD'),
(NULL, 22, 'Hunky Dory', 'Davie Bowie, 1971 ', 'HYB7C', 0, 7, 'CD'),
(NULL, 23, 'Night Visions', 'Imagine Dragons, 2012', 'NSD7C', 0, 7, 'CD'),
(NULL, 24, 'Evolve', 'Imagine Dragons, 2017', 'EED7C', 0, 7, 'CD'),
(NULL, 25, 'The Number of the Beast', 'Iron Maiden, 19820', 'TTM8C', 0, 8, 'CD'),
(NULL, 26, 'Heaven and Hell', 'Black Sabbath, 1980', 'HLS8C', 0, 8, 'CD'),
(NULL, 27, 'Interstellar', 'Hans Zimmer, 2014', 'IRZ9C', 0, 9, 'CD'),
(NULL, 28, 'Titanic ', 'James Horner, 1997', 'TCH9C', 0, 9, 'CD'),
(NULL, 29, 'Inception', 'Hans Zimmer, 2010', 'INZ9C', 0, 9, 'CD'),
(NULL, 30, 'Le Seigneur des anneaux : La Communauté de l’anneau', 'Howard Shore, 2001', 'LUS9C', 0, 9, 'CD'),
(NULL, 31, 'Le Seigneur des anneaux : Les Deux Tours', 'Howard Shore, 2002', 'LSS9C', 0, 9, 'CD'),
(NULL, 32, 'Le Seigneur des anneaux : Le Retour du Roi', 'Howard Shore, 2003', 'LIS9C', 0, 9, 'CD'),
(NULL, 33, 'Ghost in the Shell', 'Clint Mansell, 2017', 'GLM9C', 0, 9, 'CD'),
(NULL, 34, 'Mass Effect 3', 'Clint Mansell, 2012', 'M3M10C', 0, 10, 'CD'),
(NULL, 35, 'Abzu', 'Austin Wintory, 2016', 'AUW10C', 0, 10, 'CD'),
(NULL, 36, 'Terminator', 'James Cameron, 1984 Avec : Arnold Schwarzenegger, Michael Bienh, Linda Hamilton', 'TRC3D', 0, 3, 'DVD'),
(NULL, 37, 'Interstellar', 'Christopher Nolan, 2014 Avec : Matthew MacConaughey, Anne Hathaway', 'IRN3D', 0, 3, 'DVD'),
(NULL, 38, 'Pirate des Caraïbes : La malédiction du Black Pearl', 'Gore Verbinsky, 2003 Avec : Johnny Depp, Orlando Bloom, Keira Knightley, Goeffrey Rush', 'PLV5D', 0, 5, 'DVD'),
(NULL, 39, 'Pirate des Caraïbes : Le Secret du coffre maudit', 'Gore Verbinsky, 2006 Avec : Johnny Depp, Orlando Bloom, Keira Knightley', 'PTV5D', 0, 5, 'DVD'),
(NULL, 40, 'Pirate des Caraïbes : Jusqu’au Bout du Monde', 'Gore Verbinsky, 2007 Avec : Johnny Depp, Orlando Bloom, Keira Knightley, Goeffrey Rush', 'PEV5D', 0, 5, 'DVD'),
(NULL, 41, 'Monthy Python : Sacré Graal', 'Terry Gilliam - Terry Jones, 1975 Avec : Graham Chapman, John Cleese, Terry Gilliam, Eric Idle', 'MLG11D', 0, 11, 'DVD'),
(NULL, 42, 'Le Dictateur', 'Charlie Chaplin, 1940 Avec : Charlie Chaplin', 'LRC11D', 0, 11, 'DVD'),
(NULL, 43, 'Shaun of the Dead', 'Edgar Wright, 2004 Avec : Simon Pegg, Kate Ashfield, Nick Frost, Lucy Davis', 'SDW11D', 0, 11, 'DVD'),
(NULL, 44, 'Le Chant du loup', 'Antonin Baudry, 2019 nAvec : François Civil, Omar Sy, Mathieu Kassovitz, Reda Kateb', 'LPB12D', 0, 12, 'DVD'),
(NULL, 45, 'John Wick', 'Chad Stahelski, 2014 Avec : Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe', 'JKS12D', 0, 12, 'DVD'),
(NULL, 46, 'Shutter Island', 'Martin Scorsese, 2010 Avec : Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley', 'SDS12D', 0, 12, 'DVD'),
(NULL, 47, ' Full Metal Jacket', 'Stanley Kubrick, 1987 Avec : Matthew Modine, Adam Baldwin, Vincent D’Onofrio', 'FKK13D', 0, 13, 'DVD'),
(NULL, 48, 'Tu ne tueras point ', 'Mel Gibson, 2016 Avec : Andrew Garfield, Vince Vaughn, Sam Worthington, Teresa Palmer', 'TTG13D', 0, 13, 'DVD'),
(NULL, 49, 'American Sniper', 'Clint Eastwood, 2014 Avec : Bradley Cooper, Sienna Miller, Jake McDorman', 'ARE1D', 0, 1, 'DVD');

INSERT INTO `image` (`id_image`, `nom`, `description_image`, `path`) VALUES
(NULL, 'la fleche noire.jpg', 'La fleche noire', '../../img/la fleche noire.jpg'),
(NULL, 'la maison a vapeur.jpg', 'La Maison a vapeur', '../../img/la maison a vapeur.jpg'),
(NULL, 'voyage.jpg', 'Voyage au centre de la Terre', '../../img/voyage.jpg'),
(NULL, 'bovary.jpeg', 'Madame Bovary', '../../img/bovary.jpeg'),
(NULL, 'germinal.jpg', 'Germinal', '../../img/germinal.jpg'),
(NULL, 'robinson.jpg', 'Robinson Crusoé', '../../img/robinson.jpg'),
(NULL, 'vie aventureuse.jpg', 'Ma vie aventureuse', '../../img/vie aventureuse.jpg'),
(NULL, 'une autobiographie.jpeg', 'Une autobiographie', '../../img/une autobiographie.jpeg'),
(NULL, 'le chien.jpg', 'Le chien des Baskerville', '../../img/le chien.jpg'),
(NULL, 'double assassinat.jpg', 'Double assassinat dans la rue Morgue', '../../img/double assassinat.jpg'),
(NULL, 'crime de l''orient express.jpg', 'Le crime de l’Orient Express', '../../img/crime de l''orient express.jpg'),
(NULL, 'le mystère.jpg', 'Le mystère de la chambre Jaune', '../../img/le mystère.jpg'),
(NULL, 'le vieil homme.jpg', 'Le Vieil Homme et la Guerre', '../../img/le vieil homme.jpg'),
(NULL, 'fondation.jpg', 'Fondation', '../../img/fondation.jpg'),
(NULL, '451.jpg', 'Fahrenheit 451', '../../img/451.jpg'),
(NULL, 'american sniper book.jpg', 'American Sniper book', '../../img/american sniper book.jpg'),
(NULL, 'nevermind.jpg', 'Nevermind', '../../img/nevermind.jpg'),
(NULL, 'dark side.jpg', 'The Dark Side of the Moon', '../../img/dark side.jpg'),
(NULL, 'highway to hell.jpg', 'Highway to Hell', '../../img/highway to hell.jpg'),
(NULL, 'back in black.jpg', 'Back in Black', '../../img/back in black.jpg'),
(NULL, 'abbey road.jpg', 'Abbey Road', '../../img/abbey road.jpg'),
(NULL, 'hunky dory.jpg', 'Hunky Dory', '../../img/hunky dory.jpg'),
(NULL, 'night visions.jpg', 'Night Visions', '../../img/night visions.jpg'),
(NULL, 'evolve.jpg', 'Evolve', '../../img/evolve.jpg'),
(NULL, 'number.jpg', 'The Number of the Beast', '../../img/number.jpg'),
(NULL, 'heaven and hell.jpg', 'Heaven and Hell', '../../img/heaven and hell.jpg'),
(NULL, 'interstellarOST.jpg', 'Interstellar OST', '../../img/interstellarOST.jpg'),
(NULL, 'titanicOST.jpg', 'Titanic OSt', '../../img/titanicOST.jpg'),
(NULL, 'inceptionOST.jpg', 'Inception OST', '../../img/inceptionOST.jpg'),
(NULL, 'lotr1OST.jpg', 'Le Seigneur des anneaux : La Communauté de l’anneau OST', '../../img/lotr1OST.jpg'),
(NULL, 'lotr2OST.jpg', 'Le Seigneur des anneaux : Les Deux Tours OST', '../../img/lotr2OST.jpg'),
(NULL, 'lotr3OST.jpg', 'Le Seigneur des anneaux : Le Retour du Roi OST', '../../img/lotr3OST.jpg'),
(NULL, 'ghostOST.jpg', 'Ghost in the Shell OST', '../../img/ghostOST.jpg'),
(NULL, 'me3OST.jpg', 'Mass Effect 3 OST', '../../img/me3OST.png'),
(NULL, 'abzuOST.jpg', 'Abzu OST', '../../img/abzuOST.jpg'),
(NULL, 'terminator.jpg', 'Terminator', '../../img/terminator.jpg'),
(NULL, 'interstellar.jpg', 'Interstellar', '../../img/interstellar.jpg'),
(NULL, 'pirate1.jpg', 'Pirate des Caraïbes : La malédiction du Black Pearl', '../../img/pirate1.jpg'),
(NULL, 'pirate2.jpg', 'Pirate des Caraïbes : Le Secret du coffre maudit', '../../img/pirate2.jpg'),
(NULL, 'pirate3.jpg', 'Pirate des Caraïbes : Jusqu’au Bout du Monde', '../../img/pirate3.jpg'),
(NULL, 'sacree graal.jpg', 'Monthy Python : Sacré Graal', '../../img/sacree graal.jpg'),
(NULL, 'dictateur.jpg', 'Le Dictateur', '../../img/dictateur.jpg'),
(NULL, 'shaun.jpg', 'Shaun of the Dead', '../../img/shaun.jpg'),
(NULL, 'chant du loup.jpg', 'Le Chant du loup', '../../img/chant du loup.jpg'),
(NULL, 'john wick.jpg', 'John Wick', '../../img/john wick.jpg'),
(NULL, 'shutter island.jpg', 'Shutter Island', '../../img/shutter island.jpg'),
(NULL, 'full metal jacket.jpg', 'Full Metal Jacket', '../../img/full metal jacket.jpg'),
(NULL, 'tu ne tueras point.jpg', 'Tu ne tueras point', '../../img/tu ne tueras point.jpg'),
(NULL, 'american sniper movie.jpg', 'American Sniper movie', '../../img/american sniper movie.jpg');

INSERT INTO `genre` (`id_genre`, `nom_genre`, `description_genre`) VALUES
(NULL, 'Autobiographie', 'Biographie de la vie de l’auteur (ou de l’auteur de l’oeuvre original si l’on parle d’un film adapté d’une autobiographie)'),
(NULL, 'Policier', 'Enigme(s) que le protagoniste doit résoudre'),
(NULL, 'Science-fiction', 'Fiction reposant sur des progrès scientifiques et techniques'),
(NULL, 'Roman réaliste', 'Des personnages ancrés dans la réalité'),
(NULL, 'Aventure', 'De l’action, du dépaysement!'),
(NULL, 'Rock', 'ROCK’N ROOOOOOOOOOOLL'),
(NULL, 'Pop', 'Musique populaire'),
(NULL, 'Metal', 'Musique ne passant pas les détecteurs aux aéroports'),
(NULL, 'Movie OST', 'Bande originale d’un film'),
(NULL, 'Video Game OST', 'Bande originale d’un jeu vidéo'),
(NULL, 'Comédie', 'Film censé provoquer le rire (ou pas, selon la qualité du film)'),
(NULL, 'Thriller', 'Oeuvre basé sur le suspense pour garder le lecteur/ spectateur en haleine'),
(NULL, 'Guerre', 'Boum boum pan pan (mais avec une histoire!)');