

INSERT INTO `document` (`id`, `id_image`, `titre`, `description`, `code`, `etat`, `id_genre`, `type`) VALUES
(NULL, NULL, 'La Flèche noire', 'Robert Louis Stevenson, 1886', 'LRS5L', 0, 5, 'livre'),
(NULL, NULL, 'La Maison à vapeur', 'Jules Verne, 1880', 'LJV5L', 0, 5, 'livre'),
(NULL, NULL, 'Voyage au centre de la Terre', 'Jules Verne, 1867', 'VJV5L', 0, 5, 'livre'),
(NULL, NULL, 'Madame Bovary', 'Gustave Flaubert, 1857', 'MGF4L', 0, 4, 'livre'),
(NULL, NULL, 'Germinal ', 'Emile Zola, 1885', 'GEZ4L', 0, 4, 'livre'),
(NULL, NULL, 'Robinson Crusoé', 'Daniel Defoe, 1719', 'RDD5L', 0, 5, 'livre'),
(NULL, NULL, 'Ma vie aventureuse ', 'Arthur Conan Doyle, 1932', 'MAD1L', 0, 1, 'livre'),
(NULL, NULL, 'Une autobiographie', 'Agatha Christie, 1977', 'UAC1L', 0, 1, 'livre'),
(NULL, NULL, 'Le chien des Baskerville ', 'Arthur Conan Doyle, 1902', 'LAD2L', 0, 2, 'livre'),
(NULL, NULL, 'Double assassinat dans la rue Morgue', 'Edgar Allan Poe, 1841', 'DEP2L', 0, 2, 'livre'),
(NULL, NULL, ' Le crime de l’Orient Express', 'Agatha Christie, 1934', 'LAC2L', 0, 2, 'livre'),
(NULL, NULL, 'Le mystère de la chambre Jaune', 'Gaston Leroux, 1907', 'LGL2L', 0, 2, 'livre'),
(NULL, NULL, 'Le Vieil Homme et la Guerre', 'John Scalzi, 2005', 'LJS3L', 0, 3, 'livre'),
(NULL, NULL, 'Fondation', 'Isaac Asimov, 1951', 'FIA3L', 0, 3, 'livre'),
(NULL, NULL, 'Fahrenheit 451', 'Ray Bradbury, 1953\r\n', 'FRB3L', 0, 3, 'livre'),
(NULL, NULL, 'American Sniper ', 'Chris Kyle, 2012', 'ACK1L', 0, 1, 'livre'),
(NULL, NULL, 'Nevermind', 'Nirvana, 1991\r\n', 'NDN6C', 0, 6, 'CD'),
(NULL, NULL, 'The Dark Side of the Moon', 'Pink Floyd, 1973', 'TNF6C', 0, 6, 'CD'),
(NULL, NULL, 'Highway to Hell', 'AC/DC, 1979\r\n', 'HLA6C', 0, 6, 'CD'),
(NULL, NULL, 'Back in Black', 'AC/DC, 1980\r\n', 'BKA6C', 0, 6, 'CD'),
(NULL, NULL, 'Abbey Road', 'The Beatles, 1969\r\n', 'ADB7C', 0, 7, 'CD'),
(NULL, NULL, 'Hunky Dory', 'Davie Bowie, 1971\r\n', 'HYB7C', 0, 7, 'CD'),
(NULL, NULL, 'Night Visions', 'Imagine Dragons, 2012', 'NSD7C', 0, 7, 'CD'),
(NULL, NULL, 'Evolve', 'Imagine Dragons, 2017\r\n', 'EED7C', 0, 7, 'CD'),
(NULL, NULL, 'The Number of the Beast', 'Iron Maiden, 1982\r\n', 'TTM8C', 0, 8, 'CD'),
(NULL, NULL, 'Heaven and Hell', 'Black Sabbath, 1980\r\n', 'HLS8C', 0, 8, 'CD'),
(NULL, NULL, 'Interstellar', 'Hans Zimmer, 2014', 'IRZ9C', 0, 9, 'CD'),
(NULL, NULL, 'Titanic ', 'James Horner, 1997', 'TCH9C', 0, 9, 'CD'),
(NULL, NULL, 'Inception', 'Hans Zimmer, 2010\r\n', 'INZ9C', 0, 9, 'CD'),
(NULL, NULL, 'Le Seigneur des anneaux : La Communauté de l’anneau', 'Howard Shore, 2001\r\n', 'LUS9C', 0, 9, 'CD'),
(NULL, NULL, 'Le Seigneur des anneaux : Les Deux Tours', 'Howard Shore, 2002\r\n', 'LSS9C', 0, 9, 'CD'),
(NULL, NULL, 'Le Seigneur des anneaux : Le Retour du Roi', 'Howard Shore, 2003\r\n', 'LIS9C', 0, 9, 'CD'),
(NULL, NULL, 'Ghost in the Shell', 'Clint Mansell, 2017\r\n', 'GLM9C', 0, 9, 'CD'),
(NULL, NULL, 'Mass Effect 3', 'Clint Mansell, 2012\r\n', 'M3M10C', 0, 10, 'CD'),
(NULL, NULL, 'Abzu', 'Austin Wintory, 2016\r\n', 'AUW10C', 0, 10, 'CD'),
(NULL, NULL, 'Terminator', 'James Cameron, 1984\r\nAvec : Arnold Schwarzenegger, Michael Bienh, Linda Hamilton\r\n', 'TRC3D', 0, 3, 'DVD'),
(NULL, NULL, 'Interstellar', 'Christopher Nolan, 2014\r\nAvec : Matthew MacConaughey, Anne Hathaway\r\n', 'IRN3D', 0, 3, 'DVD'),
(NULL, NULL, 'Pirate des Caraïbes : La malédiction du Black Pearl', 'Gore Verbinsky, 2003\r\nAvec : Johnny Depp, Orlando Bloom, Keira Knightley, Goeffrey Rush\r\n', 'PLV5D', 0, 5, 'DVD'),
(NULL, NULL, 'Pirate des Caraïbes : Le Secret du coffre maudit', 'Gore Verbinsky, 2006\r\nAvec : Johnny Depp, Orlando Bloom, Keira Knightley\r\n', 'PTV5D', 0, 5, 'DVD'),
(NULL, NULL, 'Pirate des Caraïbes : Jusqu’au Bout du Monde', 'Gore Verbinsky, 2007\r\nAvec : Johnny Depp, Orlando Bloom, Keira Knightley, Goeffrey Rush\r\n', 'PEV5D', 0, 5, 'DVD'),
(NULL, NULL, 'Monthy Python : Sacré Graal', 'Terry Gilliam - Terry Jones, 1975\r\nAvec : Graham Chapman, John Cleese, Terry Gilliam, Eric Idle\r\n', 'MLG11D', 0, 11, 'DVD'),
(NULL, NULL, 'Le Dictateur', 'Charlie Chaplin, 1940\r\nAvec : Charlie Chaplin\r\n', 'LRC11D', 0, 11, 'DVD'),
(NULL, NULL, 'Shaun of the Dead', 'Edgar Wright, 2004\r\nAvec : Simon Pegg, Kate Ashfield, Nick Frost, Lucy Davis\r\n', 'SDW11D', 0, 11, 'DVD'),
(NULL, NULL, 'Le Chant du loup', 'Antonin Baudry, 2019\r\nAvec : François Civil, Omar Sy, Mathieu Kassovitz, Reda Kateb\r\n', 'LPB12D', 0, 12, 'DVD'),
(NULL, NULL, 'John Wick', 'Chad Stahelski, 2014\r\nAvec : Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe\r\n', 'JKS12D', 0, 12, 'DVD'),
(NULL, NULL, 'Shutter Island', 'Martin Scorsese, 2010\r\nAvec : Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley\r\n', 'SDS12D', 0, 12, 'DVD'),
(NULL, NULL, ' Full Metal Jacket', 'Stanley Kubrick, 1987\r\nAvec : Matthew Modine, Adam Baldwin, Vincent D’Onofrio\r\n', 'FKK13D', 0, 13, 'DVD'),
(NULL, NULL, 'Tu ne tueras point ', 'Mel Gibson, 2016\r\nAvec : Andrew Garfield, Vince Vaughn, Sam Worthington, Teresa Palmer\r\n', 'TTG13D', 0, 13, 'DVD'),
(NULL, NULL, 'American Sniper', 'Clint Eastwood, 2014\r\nAvec : Bradley Cooper, Sienna Miller, Jake McDorman\r\n', 'ARE1D', 0, 1, 'DVD');